version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/cicd-back
permissions:
  - object: /var/www/
    pattern: '**'
hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: ec2-user

