version: 0.0
os: linux

files:
  - source: /
    destination: ~/cicd-back
permissions:
  - object: ~/ec2-user/
    pattern: '**'
hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/after_deploy.sh
      runas: ec2-user
