name: cicd deploy test
env:
  PROJECT_NAME: cicd-back
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.18.1 ]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Create env file
        working-directory: ./
        run: |
          touch .env	
          cat << EOF >> .env	
          ${{ secrets.ENV }}

      - name: Make tar file
        run: tar -cpvzf ./$GITHUB_SHA.tgz *
        shell: bash

#      - name: Make tar file
#        run: tar -cpvzf ./$GITHUB_SHA.tgz *
#        shell: bash
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-northeast-2
#
#      - name: Upload to S3
#        run: |
#          aws s3 cp \
#            --region ap-northeast-2 \
#            ./$GITHUB_SHA.tgz s3://bmart5-s3-bucket/$PROJECT_NAME/$GITHUB_SHA.tgz
#
#      - name: Code Deploy
#        run: aws deploy create-deployment --application-name cicd-back --file-exists-behavior OVERWRITE --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name cicd-deploy-group --s3-location bucket=cicd-bucket,bundleType=tgz,key=$PROJECT_NAME/$GITHUB_SHA.tgz
